name: Build

on:
  [push]

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pod install
      - name: Build and test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace 'CloudAccess.xcworkspace' -scheme 'CloudAccess' -destination 'OS=13.4.1,name=iPhone 11 Pro' clean test | xcpretty

  release:
    name: Deploy and draft a release
    runs-on: macos-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to CocoaPods
        run: |
          set -eo pipefail
          export LIB_VERSION=${GITHUB_REF##*/} # use shell parameter expansion to strip of 'refs/tags'
          pod lib lint
          pod trunk push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      - name: Draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            :construction: Work in Progress
          draft: true
          prerelease: false
